### PR TITLE
Minimize main thread work

### PR DESCRIPTION
**Pull request by eshaben**
The script that initializes kapa is now being rendered inline, this way we can use the `defer` attribute to load kapa after the rest of the page has been loaded.

This reduces the impact of the third-party code and minimizes the main-thread work by efficiently loading the javascript:
- For Kapa.ai - reduced main-thread time and blocking time by over 50%
- For Google CDN (for recaptcha, which is used by Kapa) - reduced main-thread time by over 30% and blocking time by over 60%

It'll be interesting to see how this transfers over to the live site, where metrics are based on actual user experiences, but we should definitely see some improvements based off this one minor change 🙂

### CODE REVIEW

**Comment by albertov19** [comment]
Hey so I built this branch and the Kapa AI Widget looks great in the main site, but then when I go to any other page it shows not OK

image

**Comment by albertov19** [comment]
I can confirm this behavior using the static docs builder also

**Comment by eshaben** [comment]
> @eshaben where/when was this added? Why am I still seeing the issue?

You pulled the latest changes and did a hard refresh (for good measure)?

**Review by albertov19 — DISMISSED** [review]
Unsure what I did, all good now!

**Comment by eshaben** [comment]
@albertov19 there were some merge conflicts I had to resolve

**Pull request merged**
