### PR TITLE
add styling for function admonition

### PR DESCRIPTION
**Pull request by eshaben**
Adds styling for a new admonition, which really allows us to have expandable content for things like pallet interfaces and API-like documentation where we can go into more details on parameters, returned data, examples, etc. for functions without overcrowding pages

This new admonition is implemented in the XCM overhaul PR: https://github.com/moonbeam-foundation/moonbeam-docs/pull/777

### CODE REVIEW

**Comment by albertov19** [comment]
Hey @eshaben  just for posterity, can you add a picture of the before and after?

Thanks

**Comment by eshaben** [comment]
There isn't necessarily a "before" that I can provide. I am basically using expandable admonitions to create better documentation. So it doesn't look like the rest of our admonitions. But here is what the expandable feature looks like:
Screenshot 2023-10-31 at 8 48 40 AM

**Comment by albertov19** [comment]
Ahh it looks great!

**Review by albertov19 — APPROVED** [review]
LGTM

**Pull request merged**
