### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by eshaben**
This PR updates the packages to the latest compatible versions. Will need to coordinate this with the Tanssi package updates (https://github.com/papermoonio/tanssi-mkdocs/pull/11) and Opslayer.

With the latest version of material-mkdocs, a bunch of bug fixes around the `navigation.instant` feature were fixed, so now we can add it in. I haven't come across any issues with it. This feature makes it more of a single page application where the site doesn't reload every time you click on a new page. Makes the experience a bit smoother for users.

### CODE REVIEW

**Review by albertov19 — APPROVED** [review]
LGTM!

**Comment by eshaben** [comment]
@albertov19 I fixed two things, so this needs to be reviewed again, please! It fixes: 

1) the sticky header so it actually sticks! 😆  the build, node operators, etc. menu at the top should stay there as you scroll down the page. this was messed up when I applied the last fix for the safari issue
2) the double footer issue has been resolved. for some reason the footer was rendered from two different places, so this forces it to render from the same place on the home page and all of the index and content pages, which is in the `container` block

**Review by albertov19 — APPROVED** [review]
LGTM!

**Comment by eshaben** [comment]
@albertov19  can you please review/approve this again? There were merge conflicts! Sorry, third time is the charm?

**Review by albertov19 — APPROVED** [review]
LGTM

**Review by albertov19 — APPROVED** [review]
LGTM (again) hahaha

**Pull request merged**
