### PR TITLE
add/update redirects for xc integration

### PR DESCRIPTION
**Pull request by eshaben**
Add redirects for changes made in: https://github.com/moonbeam-foundation/moonbeam-docs/pull/704

### CODE REVIEW

**Comment by eshaben** [comment]
It's not possible to add redirects for a specific section. I can have the links redirect to the index page, where the user can then choose Forum Templates, XC Channel Registration, or XC Asset Registration? Or I can add a section to the XC Channel Registration page for Forum Templates, b/c when `#forum-templates` is appended to the URL, it would redirect to new page and then still go to that section. So then I can just point them to the new page from that section

**Comment by albertov19** [comment]
I would link it to the index page  better :)

**Comment by eshaben** [comment]
@albertov19 done!

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
