### PR TITLE
update shade of purple on the challenge admonition

### PR DESCRIPTION
**Pull request by eshaben**
update shade of purple on the challenge admonition so it stands out a little bit more

### CODE REVIEW

**Comment by albertov19** [comment]
@eshaben can you share a picture of this to see the end result?

Thanks

**Review by albertov19 — APPROVED** [review]
LGTM!

**Comment by eshaben** [comment]
Screenshot 2023-10-30 at 1 28 03 PM

I have a feeling you already saw it, but here it is 🙂

**Comment by albertov19** [comment]
Nah I was just curious - It is a lot easier just to see it in a picture than having to compile everything etc hahaha

**Pull request merged**
