### PR TITLE
docs redesign

### PR DESCRIPTION
**Pull request by eshaben**
This PR redesigns the docs site for the Moonbeam rebrand and aims to align it with the Moonbeam Network site

Side note: there are some issues with the connect to metamask button. I've started to work on redoing that, but that will be in a separate PR

### CODE REVIEW

**Review by albertov19 — APPROVED** [review]
Looks great!

Went through some pages and checked some things randomly and it all looked good!

**Review by themacexpert — CHANGES_REQUESTED** [review]
Looks really good! I think my only hesitation is the selection behavior fades out the text rather than standing out... it's a bit different from the behavior on our current docs site so not sure if this is intentional. 

New Format (Analytics is hovered over):
Screenshot 2024-05-22 at 11 39 22 AM

Existing format (Run a Node Selected):
Screenshot 2024-05-22 at 11 40 16 AM

**Comment by eshaben** [comment]
> Looks really good! I think my only hesitation is the selection behavior fades out the text rather than standing out... it's a bit different from the behavior on our current docs site so not sure if this is intentional.

Yeah, I changed it to align with the way the moonbeam network site is. If you look at their drop-down menus, they fade out a bit when you hover over them instead of getting brighter. Even the links are that way. The only elements that aren't that way, if I am remembering correctly, are the buttons

Thank you for reviewing!! Will work on adding the new graphic this afternoon and then it'll need to be reviewed a final time 🙂

**Review by themacexpert — APPROVED** [review]

**Comment by themacexpert** [comment]
> > Looks really good! I think my only hesitation is the selection behavior fades out the text rather than standing out... it's a bit different from the behavior on our current docs site so not sure if this is intentional.
> 
> Yeah, I changed it to align with the way the moonbeam network site is. If you look at their drop-down menus, they fade out a bit when you hover over them instead of getting brighter. Even the links are that way. The only elements that aren't that way, if I am remembering correctly, are the buttons
> 
> Thank you for reviewing!! Will work on adding the new graphic this afternoon and then it'll need to be reviewed a final time 🙂

Ok sounds good to me!

**Review by themacexpert — APPROVED** [review]
LGTM 👍

**Comment by eshaben** [comment]
@albertov19 added an image

**Review by themacexpert — APPROVED** [review]
LGTM

**Pull request merged**
